# _config.yml
title: Levi's Good Eats
description: Weeknight-friendly recipes and cook cards
url: https://levirosol.github.io
baseurl: /good-eats

theme: minima
markdown: kramdown
permalink: /:categories/:title/

# Collections: use _recipes with nested folders and keep them in the URL via :path
collections:
  recipes:
    output: true
    permalink: /recipes/:path/

plugins:
  - jekyll-feed

minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/levirosol" }

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
