# _config.yml
title: Levi's Good Eats
description: Weeknight-friendly recipes and cook cards
url: https://levirosol.github.io
baseurl: /good-eats

remote_theme: mmistakes/minimal-mistakes
markdown: kramdown
permalink: /:categories/:title/

# Collections: use _recipes with nested folders and keep them in the URL via :path
collections:
  recipes:
    output: true
    permalink: /recipes/:path/

include: ["_pages"]

plugins:
  - jekyll-feed
  - jekyll-include-cache

minimal_mistakes_skin: "dirt"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules

defaults:
  # _posts
  - scope:
      path: ""
      type: recipes
    values:
      gallery: auto
      author: Levi Rosol
      author_profile: true
      layout: single
      share: true
  - scope:
      path: ""
      type: pages
    values:
      gallery: auto
      author: Levi Rosol
      author_profile: true
      layout: posts

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-X8S9EE8BMN"
    anonymize_ip: false # default
